### PR TITLE
Command restructuring

### PR DESCRIPTION
**Pull request by dimitry-ishenko**
This is phase 1 in the series of commits. This series breaks up all of the Command classes into collections of Properties. Due to resulting code reuse we eliminate over 2500 lines of duplicate code.
More importantly, this allows for the Inspector classes to also be broken up into delegates, which will come in phase 2.
The overarching purpose of all of this is to allow easy addition and modification of properties in the Command and Inspector classes. (And if I last that long the Rundown widgets will come in phase 3.)
Important: To localize the changes, I chose to use IsA type relationship (inheritance) between the Property and Command classes instead of HasA (ownership). Unfortunately, Qt does not permit multiple inheritance from QObject, so I had to move all the signals into separate class (CommandEvents), which also ended up having minimal impact on other code (had to change `&this->command` to `this->command.events()` in a few places)

### CODE REVIEW

**Comment by dimitry-ishenko** [comment]
Damnit, there is a conflict in Core.pro, but it's simple to resolve. If you want me to rebase and resubmit, I can that

**Comment by dimitry-ishenko** [comment]
@Zebiolo, in case you are waiting for phase 2, it will be a little while. My weekend is booked up with several shows.
But if you agree with the above, you can commit phase 1 by itself. At the minimum it result in reduced code size. :)

**Comment by dimitry-ishenko** [comment]
TriCaster commands are next. Unfortunately, I do not have have either of these devices. If someone could please test for regressions, I would appreciate that.

**Comment by dimitry-ishenko** [comment]
This completes phase 1 and gets rid of 3500 lines of code in the process :)

**Comment by dimitry-ishenko** [comment]
Rebased onto your master. Also converted AtemFadeToBlackCommand.

**Comment by Zebiolo** [comment]
> @Zebiolo, in case you are waiting for phase 2, it will be a little while. My weekend is booked up with > several shows.
No, i'm not waiting :). I need to test this out before merge, right now i'm deep down in something else.

**Pull request closed without merging**
