### PR TITLE
Reduce code duplication, patch set 1

### PR DESCRIPTION
**Pull request by dimitry-ishenko**
This set of patches (and future ones to come) is aimed at reducing code duplication in the CasparCG Client. With my earlier attempt at this I was able to remove about 3500 lines of code.

In this set we add `AbstractProperty` class template, which encapsulates a getter and a setter, as well as `read` and `write` functions and `emit_changed` abstract virtual function. The `emit_changed` function will be overridden in derived classes to emit `changed` signal. (The reason for this function is that Qt signals/slots mechanism does not work with templates, so the `changed` signal has to be declared in the derived classes.)

In `AbstractProperties` class we add `registerReader` and `registerWriter` functions, which allow the `AbstractProperty` descendants to register themselves for automatic reading/writing to/from the XML files. The `AbstractProperties` descendants no longer need to override the `readProperties` and the `writeProperties` functions to manually read/write various properties. Everything now happens automagically.

Next we add `DEFINE_PROPERTY` macro, which aids in creation of `AbstractProperty` descendants. In this macro we create property tag, add specialization of `PropertyTraits` for this property, as well define the property class with `changed` signal and override `emit_changed` to emit the signal.

Finally we gradually convert the `AbstractCommand` to use the new properties.

Later patch sets deal with converting the remaining commands.

### CODE REVIEW

**Comment by dotarmin** [comment]
@dimitry-ishenko Thanks for the patch set! I will look into it as soon as possible! :+1:

**Comment by dimitry-ishenko** [comment]
@dotarmin thank you. I should have the next batch ready by tomorrow I think

**Comment by hummelstrand** [comment]
Dmitrij,

That is an impressive pull request, thanks for your work!


-- 

     Jonas Hummelstrand
     http://SuperFly.tv
     +46-733-970000

**Comment by dimitry-ishenko** [comment]
Thanks @hummelstrand. I have the next set ready. It's in my delegate2 branch. And that's where the real magic starts happening -- we nuke over 3000 lines of code without losing any functionality. As soon as @dotarmin reviews and applies this set, I will cue up the next one.
My rough roadmap is as follows:
1. Finish converting the remaining commands (Atem, Panasonic, Sony, Spyder and TriCaster)
2. Do similar handling with the InspectorWidgets, which should also yield a major code reduction
3. Add Auto Step property to several commands (movie, audio, still, etc)
4. Add CustomShellCommand (to launch shell scripts, etc)
...

**Comment by dimitry-ishenko** [comment]
@dotarmin sorry I just noticed that my pull request was slightly out of date, so I just rebased it a minute ago. If you have previously pulled it, please refresh. (The change is very minor -- I removed unnecessary owner check in `AbstractProperty` ctor, but some of the commit numbers have changed.) Thank you

**Comment by dotarmin** [comment]
@dimitry-ishenko, no problems! To be honest, I haven't checked it yet more than just skimmed through the patch set in general. 

I'll update you soon! Once again, thank you for the time and effort you spend!

**Comment by dimitry-ishenko** [comment]
@dotarmin no worries, take your time -- I am not rushing.

I do have set 2 and 3 ready in my `delegate2` and `delegate3` branches, which altogether will make the Client over 5000 (!) lines slimmer :dancer: 

That completes the command refactoring and I will now move onto the Inspector widgets.

**Comment by dimitry-ishenko** [comment]
@dotarmin can I encourage you to take a look at this patch set? I've got a lot more stuff ready for you. This patch set is just for warm-up :) Thank you.

**Comment by dimitry-ishenko** [comment]
With my latest `delegate4` branch we are now losing over 16000 lines of code. The Client is going on a serious diet

**Comment by dotarmin** [comment]
@dimitry-ishenko Warm-up? 😅 
I haven't forgotten about your patch set. I like how you think about abstraction and code duplication, but the most important thing is to try to keep the high quality of the client and not to focus on minimizing the number of code lines as the primary goal (even if a diet is good from time to time).

It would be more preferable with smaller pull request in the future regarding code refactoring that hasn't been discussed.

**Comment by jesperstarkar** [comment]
The "size"/complexity of this PR should be judged by looking into how many implementations of featurers it change, not the amount of code. As I see it, it "just" removes a ton of duplicates, and that can't be too complex to merge and accept?

**Comment by dotarmin** [comment]
And it isn't judged by the "size". 
I think @dimitry-ishenko has done a great job but whats important to take into consideration is the fact that it changes the architecture of the client partially. 

@Jesper, generally speaking, just because you minimize the number of code lines doesn't mean it's better.

**Comment by dimitry-ishenko** [comment]
@dotarmin code reduction is not my end goal. For some time I've wanted to add features to the Client, but refrained from doing so for the simple fact that it would require me to copy-pasta several hundred lines of existing code in order to just tweak a few things.

In its current state the Client code is very complex, has a lot of unnecessary duplication and is very hard to contribute to. So, I've decided that instead of adding hundreds and hundreds more lines of code, I will first help refactor the code to make it less complex, reduce code duplication and make it more understandable and easier to contribute to.

Now, in terms of my patches and pull requests:
1. I try to maintain the general architecture of the Client, whenever possible. However, some small changes are necessary in order to achieve the above goals.
2. My patches are "self-contained". In other words, you can take the 1st patch, review it and apply it by itself and it will not break the existing code. Take the next patch, and do the same. And so on. This way the code can be compiled after each patch and `git bisect` can be used later on to track down any bugs.

So, again, all you have to do is take the first patch, review it, test as necessary and apply. When you feel comfortable, take the next one, etc.

Some of the patches in this PR are "large-ish" due to the fact that `AbstractCommand` is used in lot of code. But again, I broke them down as much as I could without breaking the code compile-ability.

My other PRs have more patches, but they are very small.

**Comment by dimitry-ishenko** [comment]
@dotarmin if you are not interested in my patches, please let me know, so I don't spend any more time on them. We only use about 10% of the Client's functionality for our purposes, but I was willing to spend the time to clean up the code base, so that others can also benefit from it.
However, if there is no interest in it, I'd rather write my own client that does exactly what we want.
Please let me know either way. There are no hurt feelings, I just need to know, so I can make a decision which way to proceed. Thank you.

**Comment by mauricev78** [comment]
Well i think removing redundant code makes the complete code
better readable and understandable which is in my opinon called maintenance.
which is always a good thing! That not a lot off people like to do soo thumbs up from my side

**Comment by dotarmin** [comment]
@dimitry-ishenko First of all, I missed your reply totally, sorry for that! @hummelstrand Thanks for letting me know! You shouldn't feel like you feel. Off course the project is interested in all contributions, and so are we. Unluckily I missed your two last comments and that's why you haven't got any response from my side! It's totally by bad! We are all on the same page regarding code duplication, abstraction etc. but the fact is that i honestly didn't have any time to test your patch.  Last week I was on vacation but know I'm back again. I will check your patch, which I already have skimmed! :)

I would rather see that this patch becomes a part of the next CasparCG Client version (not 2.0.9) if all tests passes as expected. And once again, sorry for missing your two comments, and same to @mauricev78.

**Comment by dimitry-ishenko** [comment]
@dotarmin no worries man, and thanks for answering.

In the meantime I've been busy writing the timer app (https://github.com/dimitry-ishenko-casparcg/timer) and an app for the new X-keys controller we just got (https://github.com/dimitry-ishenko/baker).

Once I get it all up and running I will get back onto the Client. Thanks again.

**Pull request closed without merging**
