### PR TITLE
Autostep feature for select widgets

### PR DESCRIPTION
**Pull request by dimitry-ishenko**
This is a sampling for auto step feature. Same as previously, I've added it for the widgets that I use most of the time (ie, video, audio, image, FTB and custom command).

Please let me know what you think.

### CODE REVIEW

**Comment by jesperstarkar** [comment]
THIS is interesting!

**Comment by dimitry-ishenko** [comment]
And useful :)

**Comment by TomKaltz** [comment]
Can you explain a little bit about this. I'm out of the loop.

On Saturday, September 12, 2015, Dimitry Ishenko <notifications@github.com>
wrote:

> And useful :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CasparCG/Client/pull/167#issuecomment-139825177>.
>


-- 
Thomas Kaltz III
586-214-7150
Sent from Gmail Mobile

**Comment by dimitry-ishenko** [comment]
If you enable Auto Step and press F2 (or any other command) the cursor will auto step to the next item. Currently only groups can do that.

**Comment by jesperstarkar** [comment]
Are you able to do autoplay as well?

**Comment by dimitry-ishenko** [comment]
Hmm... it probably requires more knowledge of the Client's inner workings than I currently have :) What about just using groups?

**Comment by dimitry-ishenko** [comment]
Just realized, I should add the arrow down like the groups have, when auto step is on

**Comment by dimitry-ishenko** [comment]
OK fixed that

**Comment by Zebiolo** [comment]
Impressive!

It would be nice to have AutoStep on all items, don't you think ;)

**Comment by dimitry-ishenko** [comment]
@Zebiolo yes, that's right! :) This was just a sampling to get your (and others') feedback on this feature and secondly, to get it into my production version of the Client, so I can start using it.

**Comment by Zebiolo** [comment]
@Zebiolo<https://github.com/Zebiolo> yes, that's right! :) This was just a sampling to get your (and others') feedback on this feature and secondly, to get it into my production version of the Client, so I can start using it.

Keep up the good work. I'll merge it when you are done.

**Comment by dimitry-ishenko** [comment]
One thing I'd like to go over. We've got a lot of code duplication going on in the Client. For example, for every widget that has the Auto Step feature, I have to add the same lines of code. My idea was to factor out common things into "sub" widgets. For example, there can be InspectorAutoStepWidget and InspectorTriggerOnNextWidget, etc. Then every widget that needs the Auto Step functionality and Trigger On Next functionality inherits from these widgets. All of the common functions can eventually be factored out into these widgets. What do you think?

**Comment by Zebiolo** [comment]
Sounds good. Keep changes small, it's easier to review.

**Comment by dimitry-ishenko** [comment]
No problem. Thank you for your time.

**Comment by dimitry-ishenko** [comment]
@Zebiolo what's the purpose of the signals inside command classes (eg, MovieCommand, AudioCommand, etc)? They are all declared private, so can only be connected from within the class. But I don't see them being connected anywhere

**Comment by Zebiolo** [comment]
On 2015-09-14 03:41, Dimitry Ishenko wrote:
> @Zebiolo what's the purpose of the signals inside command classes
> (eg, MovieCommand, AudioCommand, etc)?
They are used inside each rundown constructor, e.g:

RundownAudioWidget.cpp
[...]
QObject::connect(&this->command, SIGNAL(allowGpiChanged(bool)), this, SLOT(allowGpiChanged(bool)));
QObject::connect(&this->command, SIGNAL(loopChanged(bool)), this, SLOT(loopChanged(bool)));
QObject::connect(&this->command, SIGNAL(remoteTriggerIdChanged(const QString&)), this, SLOT(remoteTriggerIdChanged(const QString&)));
[...]

Using Q_SIGNAL inside a private block is just a fuzzy way to declare something public :)

**Comment by dimitry-ishenko** [comment]
Ah, missed that somehow...

**Comment by dimitry-ishenko** [comment]
Hrrm, QObjects don't allow multiple inheritance... That flies square in the face of my design... Oh well

**Pull request closed without merging**
