### PR TITLE
[next] Fixed audio levels, require #264 and #265.

### PR DESCRIPTION
**Pull request by Zebiolo**

### CODE REVIEW

**Comment by grahamspr86** [comment]
This doesn't seem to compile on MacOS

`../../src/Widgets/AudioMeterWidget.cpp:118:24: error: no member named 'log10' in namespace 'std'`

**Comment by Zebiolo** [comment]
This pull request is over 1 year old and outdated. I don't know why SVT didn't merge it when it was submitted, after all they paid for the change. It seems that the client is unmaintained since i left SVT. Sorry for the inconvenient it may have caused you.

**Comment by dotarmin** [comment]
@Zebiolo, because the PRs wasn't merged at time of creating those, do you want to fix the conflicts or do you want me to do it? I know the PRs are old now and that's why I'm asking :)

**Comment by Zebiolo** [comment]
I have already fix it. Poke around in my branch and you’ll find it.

**Comment by dotarmin** [comment]
I have seen it in your branch but I got confused because number of modified files diff between your fix and the PR. But if I understand u correctly I could basically cherry-pick all changes and close the PRs instead?

**Comment by Zebiolo** [comment]
Yes

Be aware that you need to update the toolchain on all platforms due to newer Qt and compiler.

**Comment by dotarmin** [comment]
> Yes
> 
> Be aware that you need to update the toolchain on all platforms due to newer Qt and compiler.

Great. Thanks. I will update the toolchain on the build servers. Thanks once again!!

**Comment by dotarmin** [comment]
Fixed by cherry-picking from the Zebiolo/client fork.

**Pull request closed without merging**
