### PR TITLE
UPDATE README

### PR DESCRIPTION
**Pull request by jpc0**
Expanded the section on building under Linux by adding
instructions what additional steps may be required to build and
not get any variable undefined errors as well as not getting a
qmake not found error.

The script itself should probably not be updated since these two
variables can be different on every config.

### CODE REVIEW

**Comment by dimitry-ishenko** [comment]
Sorry, I don't understand what you are trying to say in this sentence:

> Please make sure that the QT5.14.2 > Desktop GCC 64-bit package is being installed.

**Comment by jpc0** [comment]
Will try to think of a way to make it clearer. Want to say that in the pre-built Qt 5.14.2 binaries installer that that option should be ticked. It's not by default.

**Comment by jpc0** [comment]
I have updated the commit, hopefully it makes more sense now.

**Comment by Julusian** [comment]
The build process has been reworked so this no longer applies

**Pull request closed without merging**
