### PR TITLE
[master] Fixed compile issue on Linux.

### PR DESCRIPTION
**Pull request by Zebiolo**

### CODE REVIEW

**Comment by nerijus** [comment]
If I try to link with this PR, I get:
```
/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by /a/CasparCG/client/src/Shell/../../lib/gpio-client/lib/linux//libgpio-client.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libboost_thread.so.1.58.0, needed by /a/CasparCG/client/src/Shell/../../lib/gpio-client/lib/linux//libgpio-client.so, not found (try using -rpath or -rpath-link)
```

**Comment by Zebiolo** [comment]
This PR is not ment for the next branch.

**Comment by nerijus** [comment]
Could you please make a PR for next branch too?

**Comment by Zebiolo** [comment]
Try now.

**Comment by nerijus** [comment]
Thanks, CasparCG client from next branch launches now.

**Comment by nerijus** [comment]
Sorry, I missed that #256 exists for the next branch.

**Pull request merged**
